const wordList = [
    { word: "stellar", hint: "Relating to stars" },
    { word: "fantasy", hint: "An imaginative, fictional world" },
    { word: "freedom", hint: "The state of being free" },
    { word: "journey", hint: "A long trip or adventure" },
    { word: "enchant", hint: "To delight or captivate" },
    { word: "compass", hint: "A navigational instrument" },
    { word: "glimmer", hint: "A faint or wavering light" },
    { word: "whisper", hint: "To speak softly or quietly" },
    { word: "radiant", hint: "Shining brightly" },
    { word: "miracle", hint: "An extraordinary event" },
    { word: "mystery", hint: "Something difficult to explain" },
    { word: "blossom", hint: "The flower of a plant" },
    { word: "serenade", hint: "A musical expression of love" },
    { word: "cascade", hint: "A small waterfall" },
    { word: "vibrant", hint: "Full of energy and life" },
    { word: "eclipse", hint: "The blocking of light" },
    { word: "ancient", hint: "Very old; from the distant past" },
    { word: "gentle", hint: "Kind and tender" },
    { word: "sapphire", hint: "A precious blue gemstone" },
    { word: "galaxy", hint: "A system of stars" },
    { word: "velvet", hint: "A soft, smooth fabric" },
    { word: "lullaby", hint: "A soothing song for sleep" },
    { word: "twilight", hint: "The time of fading light" },
    { word: "harvest", hint: "The gathering of crops" },
    { word: "glisten", hint: "To shine with sparkling light" },
    { word: "tranquil", hint: "Calm and peaceful" },
    { word: "meadow", hint: "A field of grass" },
    { word: "breeze", hint: "A gentle wind" },
    { word: "silence", hint: "The absence of sound" },
    { word: "rainbow", hint: "A colorful arc in the sky" },
    { word: "cherish", hint: "To treasure and hold dear" },
    { word: "secret", hint: "Known only to a few" },
    { word: "twinkle", hint: "To shine with rapid, intermittent light" },
    { word: "lagoon", hint: "A shallow body of water" },
    { word: "charm", hint: "A delightful quality" },
    { word: "harmony", hint: "Agreement or accord" },
    { word: "serenity", hint: "Peaceful and calm" },
    { word: "cascade", hint: "A small waterfall" },
    { word: "whimsy", hint: "Playfully quaint or fanciful" },
    { word: "velvety", hint: "Soft and smooth to the touch" }
  ]
  