const wordList = [
    { word: "stellar", hint: "Relating to stars or of exceptional quality" },
    { word: "fantasy", hint: "An imaginative, fictional world or situation" },
    { word: "freedom", hint: "The state of being free from oppression or restriction" },
    { word: "journey", hint: "A long and adventurous trip, often with significant experiences" },
    { word: "enchant", hint: "To delight or captivate with a magical or charming effect" },
    { word: "compass", hint: "A navigational instrument used to find direction" },
    { word: "glimmer", hint: "A faint or wavering light that shines softly" },
    { word: "whisper", hint: "To speak or communicate in a hushed or secretive manner" },
    { word: "radiant", hint: "Shining brightly and emitting light or joy" },
    { word: "miracle", hint: "An extraordinary event or phenomenon, often with spiritual significance" },
    { word: "mystery", hint: "Something difficult to explain or understand; a secret" },
    { word: "blossom", hint: "The flower of a plant, especially when in full bloom" },
    { word: "serenade", hint: "A musical expression of love or admiration, often performed outdoors" },
    { word: "cascade", hint: "A series of waterfalls or a continuous sequence of events" },
    { word: "vibrant", hint: "Full of energy, enthusiasm, and life; vibrant colors" },
    { word: "eclipse", hint: "The blocking of light by the interposition of a celestial body" },
    { word: "ancient", hint: "Belonging to a very distant past; old and historical" },
    { word: "gentle", hint: "Kind, tender, and showing a mild disposition" },
    { word: "sapphire", hint: "A precious blue gemstone known for its brilliance" },
    { word: "galaxy", hint: "A vast system of stars, gas, and dust bound by gravity" },
    { word: "velvet", hint: "A soft, luxurious fabric with a dense pile" },
    { word: "lullaby", hint: "A soothing song or melody to help someone fall asleep" },
    { word: "twilight", hint: "The period of the evening when the sun is below the horizon" },
    { word: "harvest", hint: "The gathering of crops from the fields; reaping" },
    { word: "glisten", hint: "To shine with sparkling light, especially from a wet or smooth surface" },
    { word: "tranquil", hint: "Calm, peaceful, and free from disturbance or commotion" },
    { word: "meadow", hint: "A field of grass or wildflowers, often used for grazing" },
    { word: "breeze", hint: "A gentle and refreshing wind, often associated with a pleasant atmosphere" },
    { word: "silence", hint: "The absence of sound or noise; stillness" },
    { word: "rainbow", hint: "A beautiful and colorful arc in the sky caused by refraction and reflection of sunlight in raindrops" },
    { word: "cherish", hint: "To hold dear and care deeply for something or someone" },
    { word: "secret", hint: "Something known or kept hidden from others; confidential" },
    { word: "twinkle", hint: "To shine with rapid, intermittent light, like stars in the night sky" },
    { word: "lagoon", hint: "A shallow body of water separated from a larger sea or ocean by a barrier" },
    { word: "charm", hint: "A delightful and attractive quality or characteristic" },
    { word: "harmony", hint: "Agreement, peace, and coexistence of different elements" },
    { word: "serenity", hint: "The state of being calm, peaceful, and untroubled" },
    { word: "cascade", hint: "A small waterfall or a continuous series of events, often flowing one after another" },
    { word: "whimsy", hint: "Playfully quaint or fanciful, often involving imaginative or unusual ideas" },
    { word: "velvety", hint: "Soft and smooth to the touch, like the texture of velvet fabric" }
  ]
  